name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-check
    env:
      TF_VAR_aws_region: "eu-west-1"
      TF_VAR_bucket_name: "${{ secrets.EXTRA_BUCKET }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}"

      - name: Terraform Plan
        run: terraform plan

  # This job runs on any push to main, including after a PR is merged
  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    env:
      TF_VAR_aws_region: "eu-west-1"
      TF_VAR_bucket_name: "${{ secrets.EXTRA_BUCKET }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
